### ISSUE TITLE
Text under the icon on Button for the Navbar component

### ISSUE THREAD

**Issue by AlexNacache** [Decathlon/vitamin-design#158]
### Duplicates ❌

- [X] I have searched the existing issues

### Libraries

- [X] Vitamin Web UI Kit
- [ ] Vitamin Android UI Kit
- [ ] Vitamin iOS UI Kit
- [ ] Vitamin Icons
- [ ] Vitamin Assets
- [ ] Vitamin Core theme (Light mode)
- [ ] Vitamin Core theme (Dark mode)
- [ ] Vitamin Base colors palette
- [ ] Vitamin Extras kit
- [ ] Not related to one Figma library

### Summary 💡

Be able to put the text of a button under the icon
<img width="801" alt="Capture d’écran 2023-01-06 à 15 50 43" src="https://user-images.githubusercontent.com/122098718/211036279-6f3024fa-ba0e-4a37-a646-6bf18ef12a7e.png">

### Dependencies 📦

For the desktop navbar
![01](https://user-images.githubusercontent.com/122098718/211036459-443980cf-588a-449e-be46-e70595b34c14.png)

### Examples 🌈

![01](https://user-images.githubusercontent.com/122098718/211036750-720cfae0-dba4-45d7-94f2-ffe3191b3e1d.png)

### Motivation 🔦

This allows us to use the "button" component

```[tasklist]
- [ ] https://github.com/Decathlon/vitamin-web/issues/1361
```

**Comment by lauthieb** [comment]
Hello,

I am writing to you because unfortunately, after investigating and starting to implement this on vitamin-web, I have to tell you that this change will cause big breaking changes and it seems complicated to me to integrate it as such.

Is it possible to keep the padding on the whole navbar as it was before? Indeed, here we can see that from now on, when adding these buttons, we cancel the padding initially applied to the whole navbar. If I do the same thing, it will cause edge effects in all the applications currently consuming our v0.

So I would like to find this compromise to keep the padding on the whole navbar please.

Also, is it possible to rename "_Bar utilities/Item button" to "_Bar utilities/Item link"? Finally, inconsistencies in the names of text variables, the layers are all called "Contact us" and yet the text displayed is not always "Contact us". 

Thank you.

Translated with www.DeepL.com/Translator (free version)

**Comment by lauthieb** [comment]
Hello @AlexNacache, thanks for your reply. I've seen this with @Decathlon/design-system-core-team-design and now it is merged on vitamin-web :)
https://github.com/Decathlon/vitamin-web/pull/1372
